server:
  port: ${PORT:8081}

spring:
  application:
    name: quotes-system
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:quote_history_db
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database: h2
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format-sql: true
    show-sql: false

  flyway:
    baseline-on-migrate: true
    enabled: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    schemas:
      - PUBLIC
